name: Check documentation
on: [push, pull_request]
jobs:
  docs:
    name: Build documentation & check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Create uv environment
        run: uv venv
      - name: Install dependencies
        run: |
          uv pip install --constraint=.github/workflows/constraints.txt pip
          uv pip install --constraint=.github/workflows/constraints.txt nox
      - name: Build documentation
        run: uv run nox --force-color --session=docs
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build
      - name: Check links
        run: uv run nox --force-color --session=linkcheck
